### ISSUE TITLE
Up the timeout to 4 hours

### ISSUE THREAD

**Issue by jklukas** [sqlalchemy-redshift/bigcrunch#2]
(Migrated from https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/issues/65)

It looks like bigcrunch is supposed to shut down 1 hour after the last created test session, and I've gotten burned by that a few times where I get distracted for about an hour and then end up waiting for another whole round of shutdown and spinup to be able to run more tests. Maybe let it keep running for 4 hours?

**Comment by graingert** [comment]
OK you're paying the bills ;)
